In [3]:
import numpy as np
from sklearn.datasets import load_diabetes

In [5]:
X,y =load_diabetes(return_X_y=True)


In [6]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [8]:
X.shape

(442, 10)

In [9]:
y.shape         # y is a output columnsklearn

(442,)

# Using sklearn linear Regression

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)


In [13]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [14]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()

In [15]:
model.fit(X_train,y_train)

LinearRegression()

In [16]:
y_pred=model.predict(X_test)

In [17]:
from sklearn.metrics import r2_score

In [18]:
r2_score(y_test,y_pred)

0.4399338661568968

In [20]:
model.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [21]:
model.intercept_

151.88331005254167

# Making own Linear Regression Class

In [22]:
class my_LR:

  def __init__(self):
    self.coef_=None
    self.intercept_=None

  def fit(self , X_train, y_train):
    X_train=np.insert(X_train,0,1,axis=1)

    # calculate the coef_
    betas=np.linalg.inv(np.dot(X_train.T , X_train)) . dot (X_train.T) . dot (y_train)

    self.intercept_ = betas[0]
    self.coef_ = betas[1:]

  def predict (self, X_test):
    return np.dot(X_test,self.coef_)+self.intercept_
    


In [25]:
model1=my_LR()

In [26]:
model1.fit(X_train,y_train)

In [27]:
X_train.shape

(353, 10)

In [28]:
np.insert(X_train,0,1,axis=1).shape

(353, 11)

In [29]:
y_pred=model1.predict(X_test)

In [30]:
r2_score(y_test,y_pred)

0.43993386615689634

In [31]:
model1.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [32]:
model1.intercept_

151.88331005254165